# Introduction to NumPy

In [1]:
import numpy as np

In [2]:
print("numpy version:", np.__version__)

numpy version: 1.18.2


In [3]:
# define array using np.array
arr_int = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_int)
print("type:", type(arr_int), "shape:", arr_int.shape)
print("axis 0:", arr_int.shape[0], "axis 1:", arr_int.shape[1])
print("length:", len(arr_int))

arr1d_float = np.array([.1, .2, .3, .4])
print(arr1d_float)
print("type:", type(arr1d_float), "shape:", arr1d_float.shape)
print("axis 0:", arr1d_float.shape[0])
print("length:", len(arr1d_float))

arr3d_int = np.array([[[1, 2], [3, 4], [.1, .2]], [[5, 6], [7, 8], [.5, .6]]])
print(arr3d_int)
print("type:", type(arr3d_int), "shape:", arr3d_int.shape)
print(
    "axis 0:", arr3d_int.shape[0],
    "axis 1:", arr3d_int.shape[1],
    "axis 2:", arr3d_int.shape[2]
)
print("length:", len(arr3d_int))

[[1 2 3]
 [4 5 6]]
type: <class 'numpy.ndarray'> shape: (2, 3)
axis 0: 2 axis 1: 3
length: 2
[0.1 0.2 0.3 0.4]
type: <class 'numpy.ndarray'> shape: (4,)
axis 0: 4
length: 4
[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]]

 [[5.  6. ]
  [7.  8. ]
  [0.5 0.6]]]
type: <class 'numpy.ndarray'> shape: (2, 3, 2)
axis 0: 2 axis 1: 3 axis 2: 2
length: 2


In [4]:
arr_zeros = np.zeros((2, 3))
print(arr_zeros, arr_zeros.dtype, type(arr_zeros), arr_zeros.shape)

arr_ones = np.ones((2, 4))
print(arr_ones, arr_ones.dtype, type(arr_ones), arr_ones.shape)

arr_arange = np.arange(1, 2, .1)
print(arr_arange, arr_arange.dtype, type(arr_arange), arr_arange.shape)

arr_empty = np.empty((100, 100))
print(arr_empty, arr_empty.dtype, type(arr_empty), arr_empty.shape)

[[0. 0. 0.]
 [0. 0. 0.]] float64 <class 'numpy.ndarray'> (2, 3)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64 <class 'numpy.ndarray'> (2, 4)
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9] float64 <class 'numpy.ndarray'> (10,)
[[1.11465519e-311 1.11474400e-311 0.00000000e+000 ... 3.18299369e-313
  1.18575755e-322 1.11465590e-311]
 [4.94065646e-324 0.00000000e+000 3.60739285e-313 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 ...
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]] float64 <class 'numpy.ndarray'> (100, 100)


In [5]:
dummy_list = [[1, 2, 3], [4, 5, 6]]
print("list:", dummy_list)
print("array:", arr_int)

# indexing & slicing
print(dummy_list[0][0], dummy_list[0][:2])
print(arr_int[0, 0], arr_int[0, :2])
print(arr_int[::-1, ::-1])

list: [[1, 2, 3], [4, 5, 6]]
array: [[1 2 3]
 [4 5 6]]
1 [1, 2]
1 [1 2]
[[6 5 4]
 [3 2 1]]


In [6]:
# ndim and size of ndarray
print("num of dimension:", arr_int.ndim)
print("num of dimension:", arr3d_int.ndim)

print("total items:", arr_int.size)
print("total items:", arr3d_int.size)

num of dimension: 2
num of dimension: 3
total items: 6
total items: 12


In [7]:
# flatten
print("before flatten:", arr_int)
print("after flatten:", arr_int.flatten())

before flatten: [[1 2 3]
 [4 5 6]]
after flatten: [1 2 3 4 5 6]


In [8]:
np.array([10, 11, 12]).shape, np.array([[10, 11, 12]]).shape, np.array([[10], [11]]).shape

((3,), (1, 3), (2, 1))

In [9]:
# append, concatenate, and delete
print(np.append(arr1d_float, [10, 11, 12]))
print(np.append(arr_int, [[10, 11, 12]], axis=0))
print(np.append(arr_int, [[10], [11]], axis=1))
print(np.append(arr_int, arr_int, axis=0))
print(np.append(arr_int, arr_int, axis=1))

print(np.concatenate([arr_int, arr_int, arr_int], axis=1))
print(np.concatenate([arr_int, arr_zeros], axis=0))
print(np.concatenate([arr_zeros, arr_int], axis=1))

print(arr3d_int)
print(np.delete(arr3d_int, 1, axis=0))
print(np.delete(arr3d_int, -1, axis=1))

[ 0.1  0.2  0.3  0.4 10.  11.  12. ]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 1. 2. 3.]
 [0. 0. 0. 4. 5. 6.]]
[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]]

 [[5.  6. ]
  [7.  8. ]
  [0.5 0.6]]]
[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]]]
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


In [10]:
# reshape, resize
print(arr3d_int, arr3d_int.shape)
print(arr3d_int.flatten())
print(np.reshape(arr3d_int, (6, 2)), np.reshape(arr3d_int, (6, 2)).ndim)
print(np.reshape(arr3d_int, (6, 1, 2)), np.reshape(arr3d_int, (6, 1, 2)).ndim)
print(np.reshape(arr3d_int, (1, 6, 2)), np.reshape(arr3d_int, (1, 6, 2)).ndim)
print(arr3d_int.reshape((3, 2, 2)))

print(np.resize(arr3d_int, (5, 3)))
# print(arr3d_int.resize((3, 5)))

[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]]

 [[5.  6. ]
  [7.  8. ]
  [0.5 0.6]]] (2, 3, 2)
[1.  2.  3.  4.  0.1 0.2 5.  6.  7.  8.  0.5 0.6]
[[1.  2. ]
 [3.  4. ]
 [0.1 0.2]
 [5.  6. ]
 [7.  8. ]
 [0.5 0.6]] 2
[[[1.  2. ]]

 [[3.  4. ]]

 [[0.1 0.2]]

 [[5.  6. ]]

 [[7.  8. ]]

 [[0.5 0.6]]] 3
[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]
  [5.  6. ]
  [7.  8. ]
  [0.5 0.6]]] 3
[[[1.  2. ]
  [3.  4. ]]

 [[0.1 0.2]
  [5.  6. ]]

 [[7.  8. ]
  [0.5 0.6]]]
[[1.  2.  3. ]
 [4.  0.1 0.2]
 [5.  6.  7. ]
 [8.  0.5 0.6]
 [1.  2.  3. ]]


In [11]:
print(arr1d_float.shape)

arr2d_float = arr1d_float[:, np.newaxis]
print(arr2d_float, arr2d_float.shape)
print(arr1d_float[None])

print(arr3d_int[:, :, :, np.newaxis].shape)
print(arr3d_int[:, np.newaxis, ...].shape)    # ellipsis

(4,)
[[0.1]
 [0.2]
 [0.3]
 [0.4]] (4, 1)
[[0.1 0.2 0.3 0.4]]
(2, 3, 2, 1)
(2, 1, 3, 2)


In [12]:
# transpose
print(arr_int)
print(arr_int.T)
print(np.transpose(arr_int))
print(arr_int.reshape(arr_int.shape[1], arr_int.shape[0]))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]
 [5 6]]


In [13]:
# mathematics operation
print(dummy_list + dummy_list)
print(arr_int + arr_int)
print(arr3d_int * 10)
print(np.round(arr1d_float * arr1d_float, decimals=1))
print(arr_int * arr_int)
print(arr_int / arr_int)

print(arr_int)
print(arr_int.sum(keepdims=True))

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[[10. 20.]
  [30. 40.]
  [ 1.  2.]]

 [[50. 60.]
  [70. 80.]
  [ 5.  6.]]]
[0.  0.  0.1 0.2]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]]
[[21]]


In [14]:
print(arr1d_float, arr1d_float)
print(np.dot(arr1d_float, arr1d_float))
print(np.dot(arr3d_int, 10))

print(arr_int)
print(np.dot(arr_int, arr_int.T))

print(np.matmul(arr_int.T, arr_int))
print(np.matmul(arr_int, arr_int.T))
# print(np.einsum("ij,jk->ik", arr_int, arr_int))

[0.1 0.2 0.3 0.4] [0.1 0.2 0.3 0.4]
0.30000000000000004
[[[10. 20.]
  [30. 40.]
  [ 1.  2.]]

 [[50. 60.]
  [70. 80.]
  [ 5.  6.]]]
[[1 2 3]
 [4 5 6]]
[[14 32]
 [32 77]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]
[[14 32]
 [32 77]]


In [15]:
np.random.seed(11111)

print(np.random.randint(10, size=(2, 3)))
print(np.random.uniform(size=(10, 10)))
print(np.random.randn(100, 100))
print(np.random.normal(1., 10, size=(5, 1)))

[[4 9 6]
 [4 5 6]]
[[0.82876716 0.03982066 0.88557674 0.56628677 0.19393237 0.14565492
  0.40990853 0.53280216 0.6360411  0.77913585]
 [0.18321795 0.71724934 0.67459823 0.62620454 0.77384383 0.90907453
  0.53260671 0.91125689 0.22051516 0.34970031]
 [0.75260033 0.28641387 0.03335391 0.36456128 0.02202929 0.03386637
  0.34900385 0.38150467 0.54428275 0.38126547]
 [0.09674482 0.4000368  0.18712556 0.27461965 0.64496604 0.25389336
  0.83903932 0.08990992 0.50659554 0.46367255]
 [0.01459832 0.29494882 0.06419573 0.70620446 0.77242503 0.28523068
  0.8208583  0.48562357 0.2011185  0.16042918]
 [0.61632528 0.45131052 0.67672624 0.69850492 0.64819182 0.7214533
  0.06246391 0.92776501 0.19019611 0.92000302]
 [0.10461661 0.80062938 0.03529367 0.34990067 0.31906082 0.45011853
  0.65560193 0.97266826 0.97510515 0.79167857]
 [0.01028781 0.52176406 0.92893453 0.99774368 0.13001397 0.52505961
  0.79647601 0.96691126 0.2066443  0.6714573 ]
 [0.48809898 0.88592363 0.67323158 0.97564678 0.4906887  0.453